<style type="text/css">
	label.shipping_time_slot {
		padding:0 5px 0 15px;
	}
	label.shipping_date{
		padding:0 5px 0 25px;
	}
	.sp-methods dd li {
	    width: 470px;
	}
	.timeslot_wrapper{
		overflow:hidden;
	}
	.timeslot_wrapper label, .timeslot_wrapper span{float:left;}
</style>
<?php 
	$arr = $this->getDisableDate();
	
	$numberday = $this->getConfigData('day_advance');
	$arrHolidays = $this->getDisableDate(true);
	
	$maxDate = date("m/d/Y");
	if (in_array($maxDate, $arrHolidays)){
		$numberday++;
	}
	
	if ($numberday) {
		if ((date('N')+$numberday)>=7) {
			$numberday = $numberday+2;
			
		}
		
		$maxDate = strtotime ( "+$numberday day" , strtotime ( $maxDate ) ) ;
		$maxDate = date ( "m/d/Y" , $maxDate );
	}
	
?>
<script>
	// array of days which need to be disabled
	var disabledDays = <?php echo $arr;?>
	
	function nationalDays(date) {
		 var m = date.getMonth(), d = date.getDate(), y = date.getFullYear();
		  for (i = 0; i < disabledDays.length; i++) {
		    if(jQuery.inArray((m+1) + '/' + d + '/' + y,disabledDays) != -1 || new Date() > date) {
		      return [false];
		    }
		  }
		 //console.log((m+1) + '/' + d + '/' + y);
		  return [true];
	}
	function noWeekendsOrHolidays(date) {
	  	var noWeekend = jQuery.datepicker.noWeekends(date);
	  	return noWeekend[0] ? nationalDays(date) : noWeekend;
	}
	jQuery(function() {
		jQuery( "#timeslot_datepicker" ).datepicker({beforeShowDay: noWeekendsOrHolidays, minDate: new Date(),maxDate: '<?php echo $maxDate?>',
				onSelect: function(dates) { 
					jQuery.ajax({
					        url: "<?php echo $this->getUrl('webqemmailcall/shipping/getTimeslot')?>",
					        type: "post",
					        data: { day: dates},
					        beforeSend: function ( xhr ) {
					            jQuery('#timeslot_loading').show();
					         },
					        success: function(response, textStatus, jqXHR){
					           
					            jQuery('#timeslot_segment').html(response);
					            jQuery('#timeslot_loading').hide();
					        }
					    });
			    } 
			});
		
	});
	
	</script>
<?php 
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$pickupData = $this->getQuote()->getPickupData();
	$_rate = $this->getRate();
	if(!isset($pickupData['store']))
	{
		$pickupData['store'] = -1;
	}
	if(!isset($pickupData['name']))
	{
		$pickupData['name'] = '';
	}
?>
<ul id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">
    <li class="timeslot_wrapper">
        <label for="<?php echo $_code ?>_store" class="shipping_time_slot"><?php echo $this->__('Timeslot') ?></label>
        <span id="timeslot_segment">
            <select class="required-entry" name="shipping_pickup[day]" style="width:170px">
            	<option value="">-- Please select date --</option>
            </select>
        </span>
        <label for="<?php echo $_code ?>_store" class="shipping_date"><?php echo $this->__("Date") ?></label>
        <span class="input-box" style="float:right">
        	<input type='text' name='shipping_pickup[timeslot_date]' class='required-entry input-text' value='<?php echo $pickupData['name']?>' id="timeslot_datepicker"/>
        	
        	<img id="timeslot_loading" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'webqem/ajax-loader.gif'?>" style="display:none"/>
        </span>
    </li>
    <?php if($this->getConfigData('dispatch_sms')):?>
    <li>
    	<span class="input-box">
            <input type="checkbox" value="1" name="shipping_pickup[sms_dispatched]" />
        </span>
        <label for="<?php echo $_code ?>_store" class="required"><?php echo $this->__('SMS when my package is dispatched') ?></label>
        
     </li>
     <?php endif;?>
     <?php if($this->getConfigData('delivery_sms')):?>
     <li>
     	<span class="input-box">
        	<input type="checkbox" value="1" name="shipping_pickup[sms_time_away]" />
        </span>
        <label for="<?php echo $_code ?>_store" class="required"><?php echo $this->__('SMS when my package is 20 minutes away') ?></label>
    </li>
    <?php endif;?>
</ul>