<style type="text/css">
	label.shipping_time_slot {
		padding:0 5px 0 15px;
	}
	label.shipping_date{
		padding:0 5px 0 25px;
	}
	.sp-methods dd li {
	    width: 470px;
	}
	#timeslot_phone_wrapper, .timeslot_wrapper{
		overflow:hidden;
	}
	#timeslot_phone_wrapper label, #timeslot_phone_wrapper span{float:left;} 
	#timeslots_sms{margin-left:10px;}
	.timeslot_wrapper label, .timeslot_wrapper span{float:left;}
</style>
<?php 
	$arr = $this->getDisableDate();
	
	$numberday = $this->getConfigData('day_advance');
	$arrHolidays = $this->getDisableDate(true);
	
	$maxDate = date("m/d/Y");
	
	if ($numberday) {
		if ((date('N')+$numberday)>=7) {
			$numberday = $numberday+2;
		}
		$maxDateStamp = strtotime ( "+$numberday day" , strtotime ( $maxDate ) ) ;
		
		$timeNow = Mage::getSingleton('core/date')->timestamp();
		foreach ($arrHolidays as $holiday) {
			if (strtotime($holiday)>=$timeNow && strtotime($holiday)<=$maxDateStamp) {
				$numberday++;
			}
		}
		
		$maxDateStamp = strtotime ( "+$numberday day" , strtotime ( $maxDate ) ) ;
		$maxDate = date ( "m/d/Y" , $maxDateStamp );
	}
	$maxDate = date('d/m/Y', strtotime($maxDate));
	
	
?>
<script>
	// array of days which need to be disabled
	var disabledDays = <?php echo $arr;?>
	
	function nationalDays(date) {
		 var m = date.getMonth(), d = date.getDate(), y = date.getFullYear();
		 
		  for (i = 0; i < disabledDays.length; i++) {
			
			if(jQuery.inArray( d + '/' + (m+1) + '/' + y,disabledDays) != -1) {
				
		      return [false];
		    }
		  }
		 
		 return [true];
	}
	function noWeekendsOrHolidays(date) {
	  	var noWeekend = jQuery.datepicker.noWeekends(date);
	  	return noWeekend[0] ? nationalDays(date) : noWeekend;
	}
	jQuery(function() {
		jQuery( "#timeslot_datepicker" ).datepicker({dateFormat: 'dd/mm/yy' ,beforeShowDay: noWeekendsOrHolidays, minDate: new Date(),maxDate: '<?php echo $maxDate?>',
				onSelect: function(dates) { 
					jQuery.ajax({
					        url: "<?php echo $this->getUrl('webqemmailcall/shipping/getTimeslot')?>",
					        type: "post",
					        data: { day: dates},
					        beforeSend: function ( xhr ) {
					            jQuery('#timeslot_loading').show();
					         },
					        success: function(response, textStatus, jqXHR){
					           
					            jQuery('#timeslot_segment').html(response);
					            jQuery('#timeslot_loading').hide();
					        }
					    });
			    } 
			});
		jQuery.ajax({
	        url: "<?php echo $this->getUrl('webqemmailcall/shipping/getTimeslot')?>",
	        type: "post",
	        data: { day: '<?php echo date('d/m/Y');?>'},
	        beforeSend: function ( xhr ) {
	            jQuery('#timeslot_loading').show();
	            jQuery('#timeslot_datepicker').val('<?php echo date('d/m/Y');?>');
	         },
	        success: function(response, textStatus, jqXHR){
	            
	            jQuery('#timeslot_segment').html(response);
	            jQuery('#timeslot_loading').hide();
	        }
	    });
		var countMailcallSms = 0;
		jQuery('#shipping_form_timeslot_timeslot input:checkbox').each(function (index) {
			 if(jQuery(this).is(':checked')) {
			    	countMailcallSms++;
			 }
		});
		jQuery('#shipping_form_timeslot_timeslot input:checkbox').click(
			 function(e){
				
			    if(jQuery(this).is(':checked')) {
			    	countMailcallSms++;
			    } else {
			    	countMailcallSms--;
			    }
			    if (countMailcallSms>0) {
					jQuery('#timeslot_phone_wrapper').show();
			    } else {
			    	countMailcallSms = 0;
			    	jQuery('#timeslot_phone_wrapper').hide();
			    }
			 }
		);
	});
	
	</script>
<?php 
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$pickupData = $this->getQuote()->getPickupData();
	$_rate = $this->getRate();
	if(!isset($pickupData['store']))
	{
		$pickupData['store'] = -1;
	}
	if(!isset($pickupData['name']))
	{
		$pickupData['name'] = '';
	}
?>
<ul id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">
    <li class="timeslot_wrapper">
    	<label for="<?php echo $_code ?>_store" class="shipping_date"><?php echo $this->__("Date") ?></label>
        <span class="input-box">
        	<input type='text' name='shipping_pickup[timeslot_date]' class='required-entry input-text' value='<?php echo $pickupData['name']?>' id="timeslot_datepicker"/>
        	<img id="timeslot_loading" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'webqem/ajax-loader.gif'?>" style="display:none"/>
        </span>
        <label for="<?php echo $_code ?>_store" class="shipping_time_slot"><?php echo $this->__('Timeslot') ?></label>
        <span id="timeslot_segment">
            <select class="required-entry" name="shipping_pickup[day]" style="width:170px">
            	<option value="">-- Please select date --</option>
            </select>
        </span>
    </li>
    <?php if($this->getConfigData('dispatch_sms')):?>
    <li>
    	<span class="input-box">
            <input type="checkbox" value="1" name="shipping_pickup[sms_dispatched]" checked/>
        </span>
        <label for="<?php echo $_code ?>_store" class="required"><?php echo $this->__('SMS when my package is dispatched') ?></label>
        
     </li>
     <?php endif;?>
     <?php if($this->getConfigData('delivery_sms')):?>
     <li>
     	<span class="input-box">
        	<input type="checkbox" value="1" name="shipping_pickup[sms_time_away]" checked/>
        </span>
        <label for="<?php echo $_code ?>_store" class="required"><?php echo $this->__('SMS when my package is 20 minutes away') ?></label>
    </li>
    <?php endif;?>
    <?php if($this->getConfigData('dispatch_sms') || $this->getConfigData('delivery_sms')):?>
    <!--<li id="timeslot_phone_wrapper" style="display:none;">-->
    <!--Commented out by Steve G @ webqem 06/12/2012-->
    <li id="timeslot_phone_wrapper" >
     	<label for="<?php echo $_code ?>_store" class="required"><?php echo $this->__('Phone Number') ?></label>
     	<span class="input-box">
        	<input type="text" value="<?php echo $this->getAddress()->getTelephone()?>" name="shipping_pickup[phone_number]" class="required-entry input-text" id="timeslots_sms"/>
        </span>
    </li>	
    <?php endif;?>
</ul>